#pragma once

// From glfw3.h
#define ACHENGINE_MOUSE_BUTTON_1         0
#define ACHENGINE_MOUSE_BUTTON_2         1
#define ACHENGINE_MOUSE_BUTTON_3         2
#define ACHENGINE_MOUSE_BUTTON_4         3
#define ACHENGINE_MOUSE_BUTTON_5         4
#define ACHENGINE_MOUSE_BUTTON_6         5
#define ACHENGINE_MOUSE_BUTTON_7         6
#define ACHENGINE_MOUSE_BUTTON_8         7
#define ACHENGINE_MOUSE_BUTTON_LAST      ACHENGINE_MOUSE_BUTTON_8
#define ACHENGINE_MOUSE_BUTTON_LEFT      ACHENGINE_MOUSE_BUTTON_1
#define ACHENGINE_MOUSE_BUTTON_RIGHT     ACHENGINE_MOUSE_BUTTON_2
#define ACHENGINE_MOUSE_BUTTON_MIDDLE    ACHENGINE_MOUSE_BUTTON_3